export enum FuelType {
  FUEL_TYPE_UNSPECIFIED = 'FUEL_TYPE_UNSPECIFIED',
  DIESEL = 'DIESEL',
  REGULAR_UNLEADED = 'REGULAR_UNLEADED',
  MIDGRADE = 'MIDGRADE',
  PREMIUM = 'PREMIUM',
  SP91 = 'SP91',
  SP91_E10 = 'SP91_E10',
  SP92 = 'SP92',
  SP95 = 'SP95',
  SP95_E10 = 'SP95_E10',
  SP98 = 'SP98',
  SP99 = 'SP99',
  SP100 = 'SP100',
  LPG = 'LPG',
  E80 = 'E80',
  E85 = 'E85',
  METHANE = 'METHANE',
  BIO_DIESEL = 'METHANE',
  TRUCK_DIESEL = 'TRUCK_DIESEL'
}

export enum PriceLevel {
  PRICE_LEVEL_UNSPECIFIED	= 'PRICE_LEVEL_UNSPECIFIED',
  PRICE_LEVEL_FREE = 'PRICE_LEVEL_FREE',
  PRICE_LEVEL_INEXPENSIVE = 'PRICE_LEVEL_INEXPENSIVE',
  PRICE_LEVEL_MODERATE = 'PRICE_LEVEL_MODERATE',
  PRICE_LEVEL_EXPENSIVE = 'PRICE_LEVEL_EXPENSIVE',
  PRICE_LEVEL_VERY_EXPENSIVE = 'PRICE_LEVEL_VERY_EXPENSIVE'
}

export enum BussinessStatus {
  BUSINESS_STATUS_UNSPECIFIED = 'BUSINESS_STATUS_UNSPECIFIED',
  OPERATIONAL = 'OPERATIONAL',
  CLOSED_TEMPORARILY = 'CLOSED_TEMPORARILY',
  CLOSED_PERMANENTLY = 'CLOSED_PERMANENTLY'
}

export enum EVConnectorType {
  EV_CONNECTOR_TYPE_UNSPECIFIED = 'EV_CONNECTOR_TYPE_UNSPECIFIED',
  EV_CONNECTOR_TYPE_OTHER = 'EV_CONNECTOR_TYPE_OTHER',
  EV_CONNECTOR_TYPE_J1772 = 'EV_CONNECTOR_TYPE_J1772',
  EV_CONNECTOR_TYPE_TYPE_2 = 'EV_CONNECTOR_TYPE_TYPE_2',
  EV_CONNECTOR_TYPE_CHADEMO = 'EV_CONNECTOR_TYPE_CHADEMO',
  EV_CONNECTOR_TYPE_CCS_COMBO_1 = 'EV_CONNECTOR_TYPE_CCS_COMBO_1',
  EV_CONNECTOR_TYPE_CCS_COMBO_2 = 'EV_CONNECTOR_TYPE_CCS_COMBO_2',
  EV_CONNECTOR_TYPE_TESLA = 'EV_CONNECTOR_TYPE_TESLA',
  EV_CONNECTOR_TYPE_UNSPECIFIED_GB_T = 'EV_CONNECTOR_TYPE_UNSPECIFIED_GB_T',
  EV_CONNECTOR_TYPE_UNSPECIFIED_WALL_OUTLET = 'EV_CONNECTOR_TYPE_UNSPECIFIED_WALL_OUTLET'
}

export enum SecondaryHoursType {
  SECONDARY_HOURS_TYPE_UNSPECIFIED = 'SECONDARY_HOURS_TYPE_UNSPECIFIED',
  DRIVE_THROUGH = 'DRIVE_THROUGH',
  HAPPY_HOUR = 'HAPPY_HOUR',
  DELIVERY = 'DELIVERY',
  TAKEOUT = 'TAKEOUT',
  KITCHEN = 'KITCHEN',
  BREAKFAST = 'BREAKFAST',
  LUNCH = 'LUNCH',
  DINNER = 'DINNER',
  BRUNCH = 'BRUNCH',
  PICKUP = 'PICKUP',
  ACCESS = 'ACCESS',
  SENIOR_HOURS = 'SENIOR_HOURS',
  ONLINE_SERVICE_HOURS = 'ONLINE_SERVICE_HOURS'
}
