const Automotive = {
  car_dealer: 'car_dealer',
  car_rental: 'car_rental',
  car_repair: 'car_repair',
  car_wash: 'car_wash',
  electric_vehicle_charging_station: 'electric_vehicle_charging_station',
  gas_station: 'gas_station',
  parking: 'parking',
  rest_stop: 'rest_stop',
};

const Business = {
  farm: 'farm',
};

const Culture = {
  art_gallery: 'art_gallery',
  museum: 'museum',
  performing_arts_theater: 'performing_arts_theater',
};

const Education = {
  library: 'library',
  preschool: 'preschool',
  primary_school: 'primary_school',
  secondary_school: 'secondary_school',
  university: 'university',
};

const Entertainment = {
  amusement_center: 'amusement_center',
  amusement_park: 'amusement_park',
  aquarium: 'aquarium',
  banquet_hall: 'banquet_hall',
  bowling_alley: 'bowling_alley',
  casino: 'casino',
  community_center: 'community_center',
  convention_center: 'convention_center',
  cultural_center: 'cultural_center',
  dog_park: 'dog_park',
  event_venue: 'event_venue',
  hiking_area: 'hiking_area',
  historical_landmark: 'historical_landmark',
  marina: 'marina',
  movie_rental: 'movie_rental',
  movie_theater: 'movie_theater',
  national_park: 'national_park',
  night_club: 'night_club',
  park: 'park',
  tourist_attraction: 'tourist_attraction',
  visitor_center: 'visitor_center',
  wedding_venue: 'wedding_venue',
  zoo: 'zoo',
};

const Finance = {
  accounting: 'accounting',
  atm: 'atm',
  bank: 'bank',
};

const FnB = {
  american_restaurant: 'american_restaurant',
  bakery: 'bakery',
  bar: 'bar',
  barbecue_restaurant: 'barbecue_restaurant',
  brazilian_restaurant: 'brazilian_restaurant',
  breakfast_restaurant: 'breakfast_restaurant',
  brunch_restaurant: 'brunch_restaurant',
  cafe: 'cafe',
  chinese_restaurant: 'chinese_restaurant',
  coffee_shop: 'coffee_shop',
  fast_food_restaurant: 'fast_food_restaurant',
  french_restaurant: 'french_restaurant',
  greek_restaurant: 'greek_restaurant',
  hamburger_restaurant: 'hamburger_restaurant',
  ice_cream_shop: 'ice_cream_shop',
  indian_restaurant: 'indian_restaurant',
  indonesian_restaurant: 'indonesian_restaurant',
  italian_restaurant: 'italian_restaurant',
  japanese_restaurant: 'japanese_restaurant',
  korean_restaurant: 'korean_restaurant',
  lebanese_restaurant: 'lebanese_restaurant',
  meal_delivery: 'meal_delivery',
  meal_takeaway: 'meal_takeaway',
  mediterranean_restaurant: 'mediterranean_restaurant',
  mexican_restaurant: 'mexican_restaurant',
  middle_eastern_restaurant: 'middle_eastern_restaurant',
  pizza_restaurant: 'pizza_restaurant',
  ramen_restaurant: 'ramen_restaurant',
  restaurant: 'restaurant',
  sandwich_shop: 'sandwich_shop',
  seafood_restaurant: 'seafood_restaurant',
  spanish_restaurant: 'spanish_restaurant',
  steak_house: 'steak_house',
  sushi_restaurant: 'sushi_restaurant',
  thai_restaurant: 'thai_restaurant',
  turkish_restaurant: 'turkish_restaurant',
  vegan_restaurant: 'vegan_restaurant',
  vegetarian_restaurant: 'vegetarian_restaurant',
  vietnamese_restaurant: 'vietnamese_restaurant',
};

const GeographicalArea = {
  administrative_area_level_1: 'administrative_area_level_1',
  administrative_area_level_2: 'administrative_area_level_2',
  country: 'country',
  locality: 'locality',
  postal_code: 'postal_code',
  school_district: 'school_district',
  political: 'political',
};

const Government = {
  city_hall: 'city_hall',
  courthouse: 'courthouse',
  embassy: 'embassy',
  fire_station: 'fire_station',
  local_government_office: 'local_government_office',
  police: 'police',
  post_office: 'post_office',
};

const HealthAndWellness = {
  dental_clinic: 'dental_clinic',
  dentist: 'dentist',
  doctor: 'doctor',
  drugstore: 'drugstore',
  hospital: 'hospital',
  medical_lab: 'medical_lab',
  pharmacy: 'pharmacy',
  physiotherapist: 'physiotherapist',
  spa: 'spa',
};

const Lodging = {
  bed_and_breakfast: 'bed_and_breakfast',
  campground: 'campground',
  camping_cabin: 'camping_cabin',
  cottage: 'cottage',
  extended_stay_hotel: 'extended_stay_hotel',
  farmstay: 'farmstay',
  guest_house: 'guest_house',
  hostel: 'hostel',
  hotel: 'hotel',
  lodging: 'lodging',
  motel: 'motel',
  private_guest_room: 'private_guest_room',
  resort_hotel: 'resort_hotel',
  rv_park: 'rv_park',
};

const PlacesOfWorship = {
  church: 'church',
  hindu_temple: 'hindu_temple',
  mosque: 'mosque',
  synagogue: 'synagogue',
};

const Services = {
  barber_shop: 'barber_shop',
  beauty_salon: 'beauty_salon',
  cemetery: 'cemetery',
  child_care_agency: 'child_care_agency',
  consultant: 'consultant',
  courier_service: 'courier_service',
  electrician: 'electrician',
  florist: 'florist',
  funeral_home: 'funeral_home',
  hair_care: 'hair_care',
  hair_salon: 'hair_salon',
  insurance_agency: 'insurance_agency',
  laundry: 'laundry',
  lawyer: 'lawyer',
  locksmith: 'locksmith',
  moving_company: 'moving_company',
  painter: 'painter',
  plumber: 'plumber',
  real_estate_agency: 'real_estate_agency',
  roofing_contractor: 'roofing_contractor',
  storage: 'storage',
  tailor: 'tailor',
  telecommunications_service_provider: 'telecommunications_service_provider',
  travel_agency: 'travel_agency',
  veterinary_care: 'veterinary_care',
};

const Shopping = {
  auto_parts_store: 'auto_parts_store',
  bicycle_store: 'bicycle_store',
  book_store: 'book_store',
  cell_phone_store: 'cell_phone_store',
  clothing_store: 'clothing_store',
  convenience_store: 'convenience_store',
  department_store: 'department_store',
  discount_store: 'discount_store',
  electronics_store: 'electronics_store',
  furniture_store: 'furniture_store',
  gift_shop: 'gift_shop',
  grocery_store: 'grocery_store',
  hardware_store: 'hardware_store',
  home_goods_store: 'home_goods_store',
  home_improvement_store: 'home_improvement_store',
  jewelry_store: 'jewelry_store',
  liquor_store: 'liquor_store',
  market: 'market',
  pet_store: 'pet_store',
  shoe_store: 'shoe_store',
  shopping_mall: 'shopping_mall',
  sporting_goods_store: 'sporting_goods_store',
  store: 'store',
  supermarket: 'supermarket',
  wholesaler: 'wholesaler',
};

const Sports = {
  AthleticField: 'athletic_field',
  FitnessCenter: 'fitness_center',
  GolfCourse: 'golf_course',
  Gym: 'gym',
  Playground: 'playground',
  SkiResort: 'ski_resort',
  SportsClub: 'sports_club',
  SportsComplex: 'sports_complex',
  Stadium: 'stadium',
  SwimmingPool: 'swimming_pool',
};

const Transportation = {
  airport: 'airport',
  bus_station: 'bus_station',
  bus_stop: 'bus_stop',
  ferry_terminal: 'ferry_terminal',
  heliport: 'heliport',
  light_rail_station: 'light_rail_station',
  park_and_ride: 'park_and_ride',
  subway_station: 'subway_station',
  taxi_stand: 'taxi_stand',
  train_station: 'train_station',
  transit_depot: 'transit_depot',
  transit_station: 'transit_station',
  truck_stop: 'truck_stop',
};

const PlaceTypeA = {
  ...Automotive,
  ...Business,
  ...Culture,
  ...Education,
  ...Entertainment,
  ...Finance,
  ...FnB,
  ...GeographicalArea,
  ...Government,
  ...HealthAndWellness,
  ...Lodging,
  ...PlacesOfWorship,
  ...Services,
  ...Shopping,
  ...Sports,
  ...Transportation,
};

const PlaceTypeB = {
  administrative_area_level_3: 'administrative_area_level_3',
  administrative_area_level_4: 'administrative_area_level_4',
  administrative_area_level_5: 'administrative_area_level_5',
  administrative_area_level_6: 'administrative_area_level_6',
  administrative_area_level: 'administrative_area_level',
  archipelago: 'archipelago',
  colloquial_area: 'colloquial_area',
  continent: 'continent',
  establishment: 'establishment',
  floor: 'floor',
  food: 'food',
  general_contractor: 'general_contractor',
  geocode: 'geocode',
  health: 'health',
  intersection: 'intersection',
  landmark: 'landmark',
  natural_feature: 'natural_feature',
  neighborhood: 'neighborhood',
  place_of_worship: 'place_of_worship',
  plus_code: 'plus_code',
  point_of_interest: 'point_of_interest',
  political: 'political',
  post_box: 'post_box',
  postal_code_prefix: 'postal_code_prefix',
  postal_code_suffix: 'postal_code_suffix',
  postal_town: 'postal_town',
  premise: 'premise',
  room: 'room',
  route: 'route',
  street_address: 'street_address',
  street_number: 'street_number',
  sublocality: 'sublocality',
  sublocality_level_1: 'sublocality_level_1',
  sublocality_level_2: 'sublocality_level_2',
  sublocality_level_3: 'sublocality_level_3',
  sublocality_level_4: 'sublocality_level_4',
  sublocality_level_5: 'sublocality_level_5',
  subpremise: 'subpremise',
  town_square: 'town_square',
};

const PlaceType = {
  ...PlaceTypeA,
  ...PlaceTypeB,
};

type PlaceTypeA = keyof typeof PlaceTypeA;
type PlaceTypeB = keyof typeof PlaceTypeB;
type PlaceType = keyof typeof PlaceType;

export { PlaceTypeA, PlaceType };